### ISSUE TITLE
Error "Buffer is not defined"

### ISSUE THREAD

**Issue by ByMykel** [DoctorMcKay/node-kvparser#1]
I'm having this error on Vue 3 with TypeScript. I guess `Buffer` is not available by default.

[Code to reproduce](https://github.com/ByMykel/valve-keyvalues-parser/pull/1)
![image](https://github.com/DoctorMcKay/node-kvparser/assets/38622893/ff16e000-0ef5-464a-80e8-d3973455641b)

**Comment by DoctorMcKay** [comment]
Please give 1.0.2 a try.

**Comment by ByMykel** [comment]
Fixed on `1.0.2`. Thank you :relaxed:
